name: Deploy lambda function
on:
  push:
    branches:
      - main
jobs:
  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate example-lambda-s3-bucket.zip
        run: |
          npm install
          zip -r example-lambda-s3-bucket-${{github.run_number}}.zip *
      - name: Upload output.zip
        uses: actions/upload-artifact@v4
        with:
          name: example-lambda-s3-bucket-${{github.run_number}}.zip
          path: example-lambda-s3-bucket-${{github.run_number}}.zip
  upload-lambda:
    runs-on: ubuntu-latest
    needs: build-lambda
    steps:
      - uses: actions/checkout@v4
      - name: Download example-lambda-s3-bucket.zip
        uses: actions/download-artifact@v4
        with:
          name: example-lambda-s3-bucket-${{github.run_number}}.zip
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Generate output.zip
        run: |
            aws s3 cp example-lambda-s3-bucket-${{github.run_number}}.zip s3://${{secrets.AWS_S3_BUCKET}}/example-lambda-s3-bucket-${{github.run_number}}.zip
  deploy:
      needs: upload-lambda
      name: deploy lambda function
      runs-on: ubuntu-latest
      steps:
      - name: AWS Lambda Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: example-lambda-s3-bucket
          s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          s3_key: example-lambda-s3-bucket-${{github.run_number}}.zip
          dry_run: true
          
    