name: Deploy lambda function
on:
  push:
    branches:
      - main
jobs:
  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate output.zip
        run: |
          npm install
          zip -r output-${{github.run_number}}.zip *
      - name: Upload output.zip
        uses: actions/upload-artifact@v2
        with:
          name: output-${{github.run_number}}.zip
          path: output-${{github.run_number}}.zip
  upload-lambda:
    runs-on: ubuntu-latest
    needs: build-lambda
    steps:
      - uses: actions/checkout@v3
      - name: Download output.zip
        uses: actions/download-artifact@v2
        with:
          name: output-${{github.run_number}}.zip
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Generate output.zip
        run: |
            aws s3 cp output-${{github.run_number}}.zip s3://${{secrets.AWS_S3_BUCKET}}/output-${{github.run_number}}.zip
          
    